[default.general]
chip = "nrf52833_xxAA"  # micro:bit V2

[default.reset]
halt_afterwards = false

[default.rtt]
enabled = true
# Scan memory for RTT control block (may be needed in SoftDevice environment)
scan_memory = true

[default.gdb]
enabled = false
